version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: bolao_mysql
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: bolao_copa
    ports:
      - "3306:3306"

  redis:
    image: redis:7.0
    container_name: bolao_redis
    ports:
      - "6379:6379"

  mongo:
    image: mongo:6.0
    container_name: bolao_mogno
    ports:
      - "27017:27017"